### ISSUE TITLE
File error when accessing new contents

### ISSUE THREAD

**Issue by krogsbell** [xbmc-danish-addons/plugin.video.drnu#101]
![image](https://github.com/user-attachments/assets/8873f2fc-9a88-487a-849c-d8cd165f30ca)

When accessing from web https://www.dr.dk/drtv/se/kender-du-typen_-med-neglekunst-og-kompromishjoerner_472869 the file is played

Regards
Hans

**Comment by TermeHansen** [comment]
Yes, saw it my self on some streams the last days, it is fixed in version 6.4.4 that I just sent for official release

https://github.com/xbmc/repo-plugins/pull/4565

**Comment by krogsbell** [comment]
Thank you very much ;-)

**Comment by krogsbell** [comment]
Tested and OK

Just one simple error found in DK strings:

msgctxt "#30905"
msgid "Debug to logfile"
msgstr "Debug i logfil"

Regards

Hans




Den tirs. 10. sep. 2024 kl. 20.04 skrev Rasmus Lundsgaard <
***@***.***>:
