### ISSUE TITLE
"unsupported_subCode" API error on Ramasjang items

### ISSUE THREAD

**Issue by TermeHansen** [xbmc-danish-addons/plugin.video.drnu#105]
Yet another weird inconsistency from dr api... 
I think I found the problem and will make a branch now

**Comment by TermeHansen** [comment]
suggested fix
https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/no_emergency

**Comment by krogsbell** [comment]
The fix solves the problem I saw with 'Netop tilføjet' and the setting 're-cache all'
