### ISSUE TITLE
API Error: unsupported_subCode

### ISSUE THREAD

**Issue by krogsbell** [xbmc-danish-addons/plugin.video.drnu#107]
When accessing the menu entry 'Netop tilføjet' you get the API Error 'unsupported_subCode'
I have only seen this error with 'Netop tilføjet' 

![image](https://github.com/user-attachments/assets/bdf6f373-e519-4137-b3fa-8c1ba0453ee2)
![image](https://github.com/user-attachments/assets/8ef371dc-e7e4-405b-b839-a45660675a3a)

Regards,
Hans

**Comment by krogsbell** [comment]
If I try to re-cash from the settings I get the same error!

**Comment by TermeHansen** [comment]
Already made an issue on it, and a suggested fix https://github.com/xbmc-danish-addons/plugin.video.drnu/issues/105
