### ISSUE TITLE
No items in "Min liste" or "Fortsæt med at se"

### ISSUE THREAD

**Issue by axyaxyfr** [xbmc-danish-addons/plugin.video.drnu#109]
I am logged in, and it shows my name in parenthesis.
Version is 12.0.1 Libreelec and plugin is version 6.4.5
The search mechanism also has no history - don't know if that's intended though :-)
Thanks for the cool plugin..

**Comment by TermeHansen** [comment]
Continue watching only works with videos that have been watched in official addons or on homepage, as we dont sent playback information back to DR from Kodi (yet).

The my list works fine for me both when adding videos or series from this addon (use context key and select add to my list), or when adding a star on DR homepage or with their official addons...

Do you have something in your my list on their homepage?

**Comment by axyaxyfr** [comment]
He, never considered checking the homepage as I never use it for watching anything, and I never use the context menu.
Using the context is just fine. Thanks for the clarification....
