### ISSUE TITLE
Live tv epg off by 1 houre

### ISSUE THREAD

**Issue by kec2** [xbmc-danish-addons/plugin.video.drnu#110]
When I go into live tv and look at fx DR1 and DR2 then the epg is off by 1 hour.

![IMG_20241030_180140](https://github.com/user-attachments/assets/238bd666-bcda-45bf-a811-5bb7ef3b2621)

Have i missed a setting or is this a bug?

**Comment by steyrs** [comment]
No issues here.

Try clearing guide data (settings, pvr & live tv).
And see if it makes a difference

**Comment by kec2** [comment]
It does not make any difference.

**Comment by TermeHansen** [comment]
I think there is indeed an issue, as DR api returns in UTC time format. I will look into a better solution that is aware of summer and winter time :smile_cat:

**Comment by kec2** [comment]
What would be great. :-)

Maybe the settings/interface/regional/timezone can be used to adjust the UTC value.

**Comment by steyrs** [comment]
Sorry to hear that..
Come to think of it - I might still be running an older version the add-on

**Comment by TermeHansen** [comment]
@kec2 Suggested fix in https://github.com/xbmc-danish-addons/plugin.video.drnu/archive/refs/tags/v6.4.6.zip

**Comment by kec2** [comment]
I just installed the update and it looks fine.
