### ISSUE TITLE
Release ny version

### ISSUE THREAD

**Issue by donkeylobster** [xbmc-danish-addons/plugin.video.drnu#12]
Jeg har opdateret master med #8 og #11 og opdateret API version til 1.4
Har oprettet et release med navnet v5.0.9

Jeg har testet det manuelt på kodi 17.5 og det ser ud til at virke.
I morgen aften (1. nov) vil jeg forsøge at sende det til kodis addon repo. Det vil være fedt hvis nogen af jer også vil teste inden det bliver sendt afsted.

**Comment by knoer** [comment]
Jeg har lige downloadet det nye, og via SSH lagt det på min Wetek Play, der kører LibreElek 8.2.0 og Kodi 17.5.

Det virker umiddelbart fint, hvis jeg starter op i DR-afdelingen.
Live TV fungerer 
Bagkatalog fungerer
Undertekster fungerer

Starter jeg op i Ramasjang eller Ultra, får jeg en fejl i addon.py: 
type 'exceptions.KeyError' 
value 'Programs'

Synes ikke lige, der følger en linje eller anden brugbar information med i fejlrapporten...?
-andet end at den angiver jeg har en version 5.07.

Er det kun mig, der oplever dette?

**Comment by donkeylobster** [comment]
Jeg havde ikke testet Ramasjang og Ultra...
Det ser ud til at være fordi 

> In version 1.4 the Programs, SelectedList and PopularList properties are no longer populated.
> https://www.dr.dk/mu-online/Help/1.4/Api/GET-api-1.4-page-tv-children-front-channel

Jeg vil forslå at blive på api v1.2 i stedet for opdatere til 1.4

**Comment by knoer** [comment]
Kort opfølgning:

Ruller jeg tilbage til 5.0.7 - og retter tvapi.py linje 121 til også at tillade https-forbindelser, så virker det igen fint med at starte universerne Ramasjang og Ultra.
Dog fungerer underteksterne så ikke.

**Comment by knoer** [comment]
Interessant info om ny API - det var jeg ikke opmærksom på..

Er der nogen fordele ved at skifte til det nye API?
-altså udover at 1.2 er det næste API i rækken, der bliver stemplet som "obsolete"?

Minder mig om en lignende problematik med DR.nu addon'et til Plex, der p.t. kun kan vise live TV pga. et skift til API 1.3 (som jeg heller ikke har haft tid til at involvere mig i)..

**Comment by donkeylobster** [comment]
Jeg har ændret tilbage til API 1.2 og oprettet et PR i Kodis addon repo: https://github.com/xbmc/repo-plugins/pull/1489

**Comment by knoer** [comment]
Super!
Så kan addon'et køre videre med samme funktionalitet som tidligere - og der er blevet mere tid til at kigge på at opdatere til API 1.4 - og få det testet godt og grundigt...

**Comment by donkeylobster** [comment]
v5.0.10 er blevet merged ind i Kodi. Min Kodi opdaterede automatisk og det ser ud til at virke som det skal.

**Comment by elgaard** [comment]
DR live holdt op med at virke på min raspberry. Jeg læste commit beskeden og ændrede tilbage til API 1.4 og så virker det fint igen. Så måske er det tid til at gå tilbage til 1.4.
