### ISSUE TITLE
Danish Live TV broken

### ISSUE THREAD

**Issue by ole-tange** [xbmc-danish-addons/plugin.video.drnu#15]
Det er uklart om det er her man rapporterer fejl med Danish Live TV Kodi Add-on.

Hvis det ikke er her, kan du så ikke lokkes til at lave en README, der peger hen i den retning?

Når jeg starter add-on-en skriver den:

"""It looks like you are not in Denmark.
One or more channels may not be playable
or other unexpected errors may occur."""

Da dette ikke er korrekt, så ville det være en hjælp, hvis der i fejlbeskeden stod, hvad man skal gøre, hvis dette er forkert. I.e. hvordan finder den ud af, hvor den tror, den er.

Når jeg vælger en af DRs kanaler, Folketinget eller Kanal Sport, så blinker skærmen kort, men vente-hjulet dukker ikke op, og der sker ikke mere.

Når jeg vælger TV2-regionerne, kommer vente-hjulet, men det bliver bare ved at vente.

Da jeg ikke har shell adgang til Kodi-devicet, så mangler jeg en guide til, hvordan jeg hiver log-information ud af dyret.

Mit problem er også beskrevet på:
https://tommy.winther.nu/wordpress/2017/11/05/fejlende-addons/#comments

Addon version: 3.1.0 (autoupdate = yes)
Hardware: X96 (Android)

**Comment by ole-tange** [comment]
På https://tommy.winther.nu/wordpress/2017/11/05/fejlende-addons/ nævner Casper nogle URLer.

Det er lykkedes mig at benytter logfile upload til at få hevet loggen ud af dyret, og min maskine kikker på URL'en:
http://dr01-lh.akamaihd.net/i/dr01_0@147054/master.m3u8?b=100-2000

Det er væsentligt forskelligt fra Caspers:
https://dr01-lh.akamaihd.net/i/live/dr01_0@147054/master.m3u8

Så mon ikke det blot er at ændre til URL'erne, som Casper kommer med?

**Comment by msj33** [comment]
Hi @ole-tange 

I guess this issue is meant for this addon, right?:
https://github.com/xbmc-danish-addons/plugin.video.dr.dk.live

And is this still an issue/relevant? Or should we close it?

All DR live channels work on the "official" DR addon in the KODI addon repo.

I can approve the PR request submitted, but I have not tested it - Also don't believe this addon is in the official KODI repo.
