### ISSUE TITLE
Catch up broken?

### ISSUE THREAD

**Issue by pank** [xbmc-danish-addons/plugin.video.drnu#20]
Did DR break catch-up?  I was able to watch shows last night (2019-01-28), but tonight nothing happens when I try to play something. 

`plugin.video.drnu` finds video urls like this (approximately): 

```python
api = Api('/tmp/')
item = api.getEpisode('deadline-2019-01-27')
video = api.getVideoUrl(item['PrimaryAsset']['Uri'])
```

Tonight, `video` is 
```
{ 'Uri': None, 'SubtitlesUri': u'https://www.dr.dk/mu-online/api/1.2/bar/5c4e34be6187a4157ce1ce01'}`
```

That doesn't look right!

It seems DR has set `Uri` to `null` and replaced it with `EncryptedUri`. (At least on the videos I tested)

E.g. [for the above](https://www.dr.dk/mu-online/api/1.2/manifest/urn:dr:mu:manifest:5c4e2f8c6187a4157ce1cdf1) this is returned:
```
{
  "Links": [
    {
      "HardSubtitlesType": "None",
      "Uri": null,
      "EncryptedUri": "010000016097da90c3e86cc6c24293e75a2f5677ab7408cd7fb0d6baabf834c52c643b33e4e4937b2513cb3413169641cb505c97a263013d4a9213e166af6e11da15296b284b2db7d236a86547aa23154259282fe74bea98bc98abe6bf22e822ef7287d7f7d90f35295186d6326ff1fa9ad53f058337d64e2e27538444bd35c921f47d41f898971bad8ca1768a9a5c8b49a085cc0d09d831db7e4eeb820e2ef5635dc747a5baedb888a86ab103e189fcbb0d5514bb4a50b787e7275e73bda81db03370d960",
      "FileFormat": "mp4",
      "Target": "HDS"
    },
    {
      "HardSubtitlesType": "None",
      "Uri": null,
      "EncryptedUri": "0100000300d4bd46bb7a4ef42afcb83a70914b389da88c42af6019e64e38bc8a16dd041821c0255df4cb58da7175fa91bca5e27b52e427b3c0467ccd95179dce7e013fc5fc6e95f4e5d2fed79ae39488ab9c7d33e73721da0f0c98dd1fb8a06452d517d73c9f0f383327640668f3db2921b1035fa00a8a1a1e57916473fd31245d508181ad4ae8e021dabd1a9006f7c8521ecc9de5cbb1085a3c83e1f0e43845e20d613a34ea261f1d60bfcd9e7b8e1fb4721c88faa94236734130c714113fafbc2138bb33e3fcc70bf37ccd62fab466e5f65194d3e579ab7a933dfa359b94bb3dbfde9f8f2c00a0585cbda411719b9a3318978ebbcee2c1740bf1049ece1ccfd84aaf4f92e25825d48514dd26873bbd543e5be09c18c3a12c21eb6657ca9011fd266dfcb1c0182377aa875ee4cbc7c10b067e7a662c30ac4035dda2eda22ebd79015a43faae7d61d4b6c32cd8667850f83f069e5aa9352f971e83910ab3eca1b4442b739f0f15adb80b023bbc32b8f973b513a53479c27fafff39496cc133332ce0f9b24492ead116e9596fbb66eaea77193ae1fd",
      "FileFormat": "mp4",
      "Target": "HLS"
    }
  ],
  "SubtitlesList": [
    {
      "Language": "Danish",
      "MimeType": "text/vtt;charset=utf-8",
      "Type": "HardOfHearing",
      "Uri": "https://www.dr.dk/mu-online/api/1.2/bar/5c4e34be6187a4157ce1ce01"
    }
  ]
}
```

`EncryptedUri` [isn't documented](https://www.dr.dk/mu-online/Help/1.4/ResourceModel?modelName=MuMediaLink).
 
Does anybody have any ideas how to get a "`DecryptedUri`"? Is DR trying to block non-sanctioned clients?  Or has `Uri` disappeared before and come back?

Thanks,
Rasmus

**Comment by TermeHansen** [comment]
I totally agree, and have come to same conclusions as you :( maybe we write and ask...

**Comment by pank** [comment]
I asked DR yesterday, but I have not received an answer explaining the
intent of the change yet.

I guess the more people that flag this issue to DR the better.

**Comment by jkiddo** [comment]
Count me in

**Comment by twinther** [comment]
Only official partners knows how to decrypt the URI, so nothing I can do.
https://tommy.winther.nu/wordpress/2019/01/30/dr-tv-addon/

**Comment by pank** [comment]
Would it be possible to delegate the work of finding an `URI` to `youtube-dl`?  It seems they [fixed the issue](https://github.com/rg3/youtube-dl/issues/19039).  (Of course it may take some time before the patch makes it to Kodi)

**Comment by TermeHansen** [comment]
Good found...
        def hex_to_bytes(hex):
            return binascii.a2b_hex(hex.encode('ascii'))

         def decrypt_uri(e):
            n = int(e[2:10], 16)
            a = e[10 + n:]
            data = bytes_to_intlist(hex_to_bytes(e[10:10 + n]))
            key = bytes_to_intlist(hashlib.sha256(
                ('%s:sRBzYNXBzkKgnjj8pGtkACch' % a).encode('utf-8')).digest())
            iv = bytes_to_intlist(hex_to_bytes(a))
            decrypted = aes_cbc_decrypt(data, key, iv)
            return intlist_to_bytes(
                decrypted[:-decrypted[-1]]).decode('utf-8').split('?')[0]

**Comment by pank** [comment]
Presumably the key could be changed in the future.  So it might be better to just let `youtube-dl` handle it. 

[`sendtokodi`](https://github.com/firsttris/plugin.video.sendtokodi) gets a recent version of `youtube-dl` automatically, although it's still a bit too old (from January 24).  However, it's not that convenient, as basically have to use Chrome to make it work.

Another option to 'cast' urls is [WebMediaShare](https://f-droid.org/en/packages/com.tobykurien.webmediashare/) plus [Kore's](https://f-droid.org/en/packages/org.xbmc.kore) play on Kodi.

Sadly, neither are as convenient as `plugin.video.drnu`...

**Comment by TermeHansen** [comment]
Got it working again by porting some of the function from youtube-dl... I'll wrap it up for a PR so other can try before merging

**Comment by pank** [comment]
Fantastic! 

Does [this](https://www.dr.dk/tv/se/bedrag/bedrag-iii/bedrag-iii-4-10) video work properly?  With `youtube-dl-git` it fetches the visually interpreted version (synstolkning). (I was trying to make `drnu` play videos via  `sendtokodi`/`youtube-dl`, but ran in to this bug...; I'm pretty sure it's a regexp gone wrong in `youtube-dl` tho).

**Comment by TermeHansen** [comment]
please try it out, It seems to work here at least

https://github.com/TermeHansen/plugin.video.drnu/commit/a672c290a75fe3d70943e70069d6846b15569a8c

**Comment by pank** [comment]
I haven't tested yet. 

On the second commit.

Did you forget to commit a file, `youtube_dl.py`?  More specifically, where do you get `decrypt_uri` from?  `decrypt_uri` is part of a class in the  `extractors/drtv.py` so presumably ` from youtube_dl import decrypt_uri` is not valid.

Further:
- if you are using the "real" `youtube_dl`, do you not need to declare a `youtube_dl` dependency somewhere, e.g. `addon.xml`?
- Nitpick: In `getVideoUrl(self, assetUri)`, you might want to ensure that `'EncryptedUri'` is a key (or `try`) in `links` to avoid `KeyError`s in case the API names are changed. Maybe it doens't matter...


Aside:  
I "solved" problem using this modified `playVideo`.  The problem is that it depends on `sendtokodi` which is not in the main repo (which probably renders this approach void), and it display an ugly pop-up whenever it plays a video.  The good thing about `sendtokodi` is that it maintains an updated `youtube-dl`, tho.

```
    def playVideo(self, slug):
        self.updateRecentlyWatched(slug)
        item = self.api.getEpisode(slug)
        dr_video = self.api.getVideoUrl(item['PrimaryAsset']['Uri'])
        video = 'plugin://plugin.video.sendtokodi/?%s' % item["PresentationUri"]
        item = xbmcgui.ListItem(path=video, thumbnailImage=item['PrimaryImageUri'])
        if ADDON.getSetting('enable.subtitles') == 'true':
            if dr_video['SubtitlesUri']:
                item.setSubtitles([dr_video['SubtitlesUri']])
        xbmcplugin.setResolvedUrl(HANDLE, video is not None, item)
```

**Comment by TermeHansen** [comment]
You are right forgot to add the youtube_dl.py (and no it is a small wrap of som of the functions I have made)
https://github.com/xbmc-danish-addons/plugin.video.drnu/commit/c7b20c40f621a152792901ec0abf36bd6c71fec5

**Comment by pank** [comment]
A quick test suggests everything is working great.  Thanks you!

My only nitpick is that I'd prefer if `youtube_dl.py` was renamed as it is slightly confusing.

Anyway, I think your approach is great.  I think it would be nice if this was merged and a new version was released.

**Comment by pank** [comment]
There's a new comment on [Tommy's blog](https://tommy.winther.nu/wordpress/2019/01/30/dr-tv-addon/).

> DR har gjort det for at beskytte deres copyright, da det var temmelig let at downloade udsendelser inden denne ændring. Det er det så stadigvæk side youtube-dl har fundet krypteringsnøglen.
Når DR skriver som de gør i deres dokumentation har jeg ikke tænkt mig at opdatere addon’en.

Maybe we should move development to a new repo and ask the Kodi maintainers to use that instead?

**Comment by msj33** [comment]
The user "krogsbell" at the kodi forums also got the addon working again on his fork:
https://forum.kodi.tv/showthread.php?tid=339922

He even have a cool feature of displaying when a series is about to expire.

Unforetunately, he does only use github for a zipped source version.
https://github.com/krogsbell/IPTV/blob/master/plugin.video.drnu-2019-02-03.zip

@twinther Care to comment, thx :-)

We could do multiple options here:

- Do a quick n' dirty merge on your existing repo :-)
and
- Reach out to DR, for trying to get an acceptance of API usage for this addon (DR seem to have opened up a bit, when it comes to open source - They even do it themselves)
or
- Move source to a new fork and keep doing, what we apparently are now allowed to do by paper terms.........not like we are doing anything illegal here with the content itself - just "breaking" a simple waiver! (But laywers might believe otherwise:-))

My kids just loves the kodi addon! - They are lost in a browser with a mouse.......pure simplicity!

/Morten

**Comment by twinther** [comment]
Well it's up to you. If you decide to submit an update to Kodi then please remove my details from addon.xml, I haven't really contributed for 2+ years now anyway.
I guess the easiest is to fork the repo or alternatively I could add you as contributors with commit access.

**Comment by TermeHansen** [comment]
How difficult would it be to have kodi point at a new repo? I mean for that reason wouldn't it be easier just to stay here and add us as contributors?

DR just replied btw.

> Hej Rasmus
> 
> DR understøtter ikke brug af 3. parts addon. Derfor kan vi ikke hjælpe med at få KODI til at virke. De addon vi bruger/understøtter finder du her på siden
> 
> Med venlig hilsen
> 
> Søren Jensen
> Programservice

**Comment by RAJensen** [comment]
> Hej Rasmus

>DR understøtter ikke brug af 3. parts addon. Derfor kan vi ikke hjælpe med at få KODI til at virke. De >addon vi bruger/understøtter finder du her på siden

>Med venlig hilsen

>Søren Jensen
>Programservice


What a bad attitude considering that they get paid by the people of Denmark by force..!
I have paid my fee and I think I have the right too choose what system I want to see the shows on.

**Comment by msj33** [comment]
Hi @twinther 

I have done this PR for fixing the encrypted streams+removing your official ownership(Making it community owned instead) - tested it locally, and it works on both Windows+LibreELEC.

https://github.com/xbmc-danish-addons/plugin.video.drnu/pull/21

I'm more than happy to keep using this repo, hence we persist all the history/issues and current PR - So if you add me as contributer, i'll handle the PR and issues going forward.

Also have some new updated DR logos to contribute for the front page of the addon - But lets focus on getting this addon working again :-)

/Morten

**Comment by twinther** [comment]
I have invited some of you as contributors, you should get an email shortly from github. If more are interested let me know.
