### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by andersenthomas** [xbmc-danish-addons/plugin.video.drnu#33]
Hi,

Are there any plans for python 3 compatibility? The upcoming Kodi Matrix will be purely based on v3 for add-ons.

**Comment by TermeHansen** [comment]
sure, I can make a PR and start testing the changes needed for python 3 with Matrix and the API changes

**Comment by maisun** [comment]
Great work, very much needed for a complete Kodi experience :)
Thanks!

**Comment by steyrs** [comment]
Any progress on this?
Use it very often - and now we have Kodi Matrix out - would be nice if it could be supported :)

**Comment by TermeHansen** [comment]
I will start it as soon as I am done with the next release that has many small fixes and improvements... If anyone of you could help with testing it would help :)

**Comment by steyrs** [comment]
@TermeHansen - I can do some testing if you like - just let me know when ;)

**Comment by TermeHansen** [comment]
thanks @steyrs, I have pinged you in #38

**Comment by TermeHansen** [comment]
I think I have a working version now, please test it out from #45

**Comment by TermeHansen** [comment]
It is now release in official channels as 5.0.14+matrix.1

**Comment by maisun** [comment]
Hi, can somebody tell me how to install the new version? I tried to reach in Kodi's official repository but couldn't find the plugin "DR TV". Do I need to download somewhere any install it manually?

**Comment by TermeHansen** [comment]
I see it in kodi 19 on Android at least... 
![Screenshot_20210307-214801_Kodi](https://user-images.githubusercontent.com/6922018/110254403-4d5e2b00-7f8f-11eb-8a28-416368cba57b.png)

**Comment by gade01** [comment]
It's at the mirrors as well.
https://mirrors.kodi.tv/addons/matrix/plugin.video.drnu/
