### ISSUE TITLE
Add-on broken in KODI add-on catalog

### ISSUE THREAD

**Issue by DKKHP** [xbmc-danish-addons/plugin.video.drnu#48]
Add-on is listed as defective in KODI add-on catalog 
Kodi 18.7 on Raspberry PI and Kodi 18.8 Linux Mint on X86

**Comment by TermeHansen** [comment]
Yes that looks weird. I just updated in Leia and reported it broken in Gotham (as I have only tested on Leia) as this is their policy. I will make an issue and report back here...

**Comment by TermeHansen** [comment]
You can grap the 5.0.13 release zip from here until it is fixed if it is

**Comment by TermeHansen** [comment]
Ok, I think it should be solved now in official addon channel for kodi, can you confirm @DKKHP ?

**Comment by gade01** [comment]
I can confirm the new version is on the mirrors now: https://mirrors.kodi.tv/addons/leia/plugin.video.drnu/

@TermeHansen Thanks so much for all your work on these addons. :)

**Comment by TermeHansen** [comment]
Alright I'll close this issue then. it will also go to matrix channel tonight. Also I made the bonanza addon work again, which also should come up tonight to
