### ISSUE TITLE
"Area Chooser" 

### ISSUE THREAD

**Issue by ABH10** [xbmc-danish-addons/plugin.video.drnu#51]
I am using Rpi3B+ with Libreelec 9.2 (Kodi 18.9) and DRTV 5.0.15.
In the context menu for the DRTV app. I have set "Start in area" to "Show area chooser".
After a reboot I will then see the Area Chooser when entering the DRTV app. and I can select what area to use.
However, if I leave DRTV and re-enter DRTV I will not see the Area Chooser again.
To see the Area Chooser I have to reboot!
It is not enough to use the context menu to set something else in "Start in area", e.g. "Ramasjang". The DRTV app will only switch to a new area or show the Area Chooser after a reboot. Is this intended behavior, or is this just happening for me, using Librelec?
This is not a new "feature" for 5.0.14 or 5.0.15.

**Comment by TermeHansen** [comment]
I think it is a feature of kodi, that you can jump to home screen other places, and when jumping back to drnu app it will tell in which level of the app it was when you left. But for testing of the app I also need it to start from scratch again and gave found that when clicking the app in add-ons -> video add-ons -> drnu addon, it will start at scratch....

But yes I think it is a feature and also nice to jump back to where you left.

**Comment by TermeHansen** [comment]
I can make a setting where i force it to go to area chooser every time if you want?

**Comment by TermeHansen** [comment]
you can try this... https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/feature/area_selector_item

**Comment by ABH10** [comment]
Thanks a lot. That link in the main menu solves the "problem". I can now visit the three areas without rebooting.

**Comment by TermeHansen** [comment]
I'll let this feature wait a bit in a pull request, to collect it together with maybe other improvements or fixes surfacing from you and others.... Let me know of other ideas or thoughts to improve.

**Comment by TermeHansen** [comment]
@ABH10 actually now that I solved another bug, I saw that the area chooser actually lies in the context menu of any item.... so I don't think it should be put as an extra item in the other lists, as I did here for you. Does the context menu work for you, or do you still think we should have the area choose item also?

**Comment by ABH10** [comment]
For me it would be a drawback, not to have the area chooser in the main menu.
I use my TV's remote control (CEC commands via HDMI to RPi) and the context menu is a little tricky to activate on the RC (special button). 
The context menu is therefore not something a normal user (like my wife) would use.
Basically I don't really understand, why the app is made this way. For me it would be natural, that you always entered the app via the area chooser. If you have kids, you will switch between the areas very often. It is as if, it is intended to select area once and then it is expected, that you never, or very seldom go to another area. But this is not the case for me at least :-)
