### ISSUE TITLE
Video playback crashes Kodi

### ISSUE THREAD

**Issue by ole-tange** [xbmc-danish-addons/plugin.video.drnu#63]
Playing https://www.dr.dk/drtv/episode/harry-palmer_301935 causes Kodi to crash.

Version: Android/Matrix

**Comment by TermeHansen** [comment]
Hi Ole

Thank you for the case, I think I saw a similar myself the other day but forgot about it...

Anyhow I am also developing / reverse engineering the new API (not this mu-online) that they now use. You can see the current state in #64. In that branch it is not crashing with the link we get from that API. So I guess this only pushes even harder to finish that development...

So if you have the skills to help, feel free to join in :)

**Comment by TermeHansen** [comment]
Ha, no, it was because I did not use the adaptive inputstream in that branch. Now that I added that part there it also crashes...

I will report bug in kodi and we can see what they say.

**Comment by TermeHansen** [comment]
https://github.com/xbmc/inputstream.adaptive/issues/963

**Comment by TermeHansen** [comment]
@ole-tange we finally found the bug and solved it in inputstream.adaptive... So I hope to push a new update that bumps inputstream.adaptive very soon.
