### ISSUE TITLE
subtitles missing with ffmpeg

### ISSUE THREAD

**Issue by pank** [xbmc-danish-addons/plugin.video.drnu#71]
It seems that with the ffmpeg  backend there are no subtitles. Maybe they are stored under a different key with the new API?

For example this program has subtitles online but they are not available in Kodi:

https://www.dr.dk/drtv/se/signe-molde-paa-udebane_-broendby_luder_336034

I don't have access to my laptop but I can have a look later.

**Comment by TermeHansen** [comment]
Ahhh yes, we rely on inputstream adaptive now to provide subtitles along with stream. I will add the old subtitle code and have it on in case of ffmpeg

**Comment by TermeHansen** [comment]
please test https://github.com/xbmc-danish-addons/plugin.video.drnu/pull/73

Though I don't see the point in using ffmpeg now...
