### ISSUE TITLE
subtitles seem to disappear with adaptive backend 

### ISSUE THREAD

**Issue by pank** [xbmc-danish-addons/plugin.video.drnu#72]
For several programs I have noticed that subtitles disappear around 3/5 way through when using the adaptive inputstream type. Maybe the video source file/URL changes and so does the URL of subtitles if it's a hls stream?

For example in this program the subtitles stop being available around minute 40-45 on Kodi. Even though they are enabled, no subtitles are actually shown.

https://www.dr.dk/drtv/se/carmen-curlers_-axels-curlers_336316

**Comment by TermeHansen** [comment]
It is an issue with inputstream adaptive in Kodi 19 (current stable), when there are empty subtitle stream files. From DR they are 60sec in size, so if there is a gab of more than 60sec with no subtitles we will loose subtitles...
I raised the issue, but I don't think they will fix it as Kodi 20 is around the corner.

I will activate the old subtitle code, where we downloaded the whole file locally as a setting. That solves it, but will give you double up on subtitle streams to choose from.

I'll write here when I have a fix ready for you to test.

**Comment by TermeHansen** [comment]
@pank  Made this:

https://github.com/xbmc-danish-addons/plugin.video.drnu/pull/73

-Can you test also?

**Comment by pank** [comment]
Thanks. I will test it tomorrow.

**Comment by TermeHansen** [comment]
@pank did you get a chance to test my solution? I would like to push this and some other small fixes out soon...

**Comment by pank** [comment]
Yes, it seems to work well when I select subtitles from file in some of 
the videos where I'd noticed subtitles were missing.

Thanks a lot!
