### ISSUE TITLE
Subtitles disappear

### ISSUE THREAD

**Issue by njrasser** [xbmc-danish-addons/plugin.video.drnu#76]
When viewing an episode from dr.dk, the subtitles suddeltly disappear. It happens randomly, sometimes after 5 minutes, sometimes after 30 minutes, and sometimes the subtitles remain during the full episode. The issue was e.g. yesterday viewing https://www.dr.dk/drtv/serie/loegnens-hus_315527. 
My Kodi is running 19.4.0 within LibreElec 10.0.2 on a RPI3.

**Comment by TermeHansen** [comment]
I'm sure it is the adaptive inputstream addon issue I have reported there. It is not in kodi Nexus, and I don't think they will fix it for kodi Matrix :(

I have activated a workaround solution in latest version (6.0.2), that needs to be set in setting (use local subtitles).

For upcomming version 6.1.0 I will probably make this default for all, but for now you need to change in settings yourself...

Let me know if it solves it for you!

**Comment by njrasser** [comment]
Hi,
Thanks for the fast answer. I have now changed the inputstream to ffmpegdirect - time will show if it helps,..

**Comment by TermeHansen** [comment]
No, not that.... Leave at inputstream, it is the "subtitles from file" setting.

![Screenshot_20221126-190008_Kodi.png](https://user-images.githubusercontent.com/6922018/204102647-cb75159b-e39d-490b-93bd-329352bb35f4.png)

**Comment by njrasser** [comment]
Far better :-) Vorks fine, until now 
Thanks
