### ISSUE TITLE
Opening "Programmer A-Å" leads to "side ikke fundet"

### ISSUE THREAD

**Issue by steyrs** [xbmc-danish-addons/plugin.video.drnu#83]
Yo folks.

Running Kodi 19.5 - and DR Addon version 6.1.1+matrix.1
When I try to open "Programmer A-Å" - I get an error stating:

"There was an error while communicating with DR NU.
Please try again later. Error message is:
{"message":"Side ikke fundet"}

Screenshot can be seen [here](https://ibb.co/pQ09NyF):

Any solution to this?
Need more information - don't hesitate to ask!
I can test a new version - if necessary :)

**Comment by TermeHansen** [comment]
Yes I also noticed. They have changed API a bit at dr.dk  - please look at https://github.com/xbmc-danish-addons/plugin.video.drnu/pull/82 and test the https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/new_settings branch for it... I've been running this for a week now, and only saw a small bug that I will see if I can get out tonight.

Let's continue the talk of that branch in the PR

**Comment by TermeHansen** [comment]
also added https://github.com/xbmc-danish-addons/plugin.video.drnu/releases/tag/v6.2.0 now

**Comment by steyrs** [comment]
I can not reproduce the error - after testing version 6.2.0.

For all I know this issue can be closed.
