### ISSUE TITLE
Porting for Home Assistant (Not really an issue)

### ISSUE THREAD

**Issue by agdamsbo** [xbmc-danish-addons/plugin.video.drnu#85]
Hi! This is really a great project. Tak!
For different reasons, I prefer to avoid using Kodi, and try to stay on Home Assistant, that I already have running. And my chromecast, that is more partner-friendly.
I am able to stream links (extracted with svtplay-dl) to my chromecast from HA, and seeing this project is all python, I would assume it would be possible to port your work to Home Assistant as a Media Source addon. My python skills are still quite limited, but are my assumptions right? Do you @TermeHansen know of any similar efforts? Or would you be able to give just a simple advice on the idea? Am I totally off? This will then be my chance to get more familiar with python.
Thank you very much! 
Andreas

**Comment by TermeHansen** [comment]
I don't have Chromecast, but do use HA. I can start a new repo and we can try to get it flying together.

I'll write here when I have set it up...

**Comment by TermeHansen** [comment]
@agdamsbo Let's continue this discussion here:

https://github.com/TermeHansen/home-assistant-drtv-play/issues/1
