### ISSUE TITLE
From 2024 a login is required for viewing archive content

### ISSUE THREAD

**Issue by lars-olsen** [xbmc-danish-addons/plugin.video.drnu#86]
This is a feature request to support login in the plugin, as from no later than 2024 q2, DR will make it mandatory to login to view archive content via drtv. 
Source: https://www.dr.dk/nyheder/seneste/fra-naeste-aar-skal-alle-logge-ind-se-drtv

**Comment by TermeHansen** [comment]
I just wrote to DR last week to ask for assistance on this topic, as they have no documentation on the API.

They have promised to get back to me, so I hope to implement this soon. I'll report here on the update.

**Comment by TermeHansen** [comment]
After 3months of waiting and asking several times for an answer we get:


> DRTV findes på flere forskellige enheder og platforme, som alle er tilknyttet DR’s login. Det sikrer en god brugeroplevelse og at de tekniske krav overholdes.
 
> KODI er ikke en platform DR understøtter, og den mulighed for at tilgå DR’s indhold, som du hidtil har benyttet dig af, vil bortfalde.

**Comment by TermeHansen** [comment]
I asked how to use this feature they have for tv-boxes etc.

https://www.dr.dk/drtv/kode

So disappointing 😒

I'll try to reverse engineer again, but if anyone can help I would be very happy...

**Comment by gade01** [comment]
This is extremely disappointing. 
I hope you can find some way to work around it, fingers crossed.

Thanks so much for looking into this.

**Comment by pank** [comment]
That is disappointing. Thanks for getting in touch with them.

I wonder if some of the devs on https://github.com/drdk/ would be more helpful? It sounds absurd that we can't at the very least get a personal API key and use that like with YouTube clients etc.

**Comment by TermeHansen** [comment]
Good news! 
I finally managed to reverse engineer the login flow in python (outside of kodi). So there is a chance that soon I will need some testing. Next up I need to polish this flow up a bit (10 chained post and get request calls to the api in the right order), and then learn when and how to refresh the token before putting it in to kodi where it is more tricky to debug :)
I'll stop for tonight, but I'll post here when I have something ready for testing...

**Comment by TermeHansen** [comment]
Ok, I think I have a first working version up in the branch [login_flow](https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/login_flow)

I have also made a pre-rease if the makes it easier to grap the zip for testing.
https://github.com/xbmc-danish-addons/plugin.video.drnu/releases/tag/v6.3.0


Please let me know if it works for you. You need to fill in username and password in setting, and then push login in the settings as well. A pop-up will tell if you managed to login. If you log in I have added "Min Liste" and "Fortsæt med at se" to the main menu. This needs to be tested a bit on how that works. I you don't login (leave the username and password empty, it just continues with anonymous tokens. Each time you push login button you will force a new request of the user token, so this is the way to switch user or to anonymous...

I will try to use this the coming weeks, to see how it works also over time with token refreshing and so on.

**Comment by lars-olsen** [comment]
første test gik ok. Login virkede, men jeg fik ikke punkterne 'min liste' og fortsæt med at se' i hovedmenuen.
Næste test gik bedre. Slettede som forsøg den profil jeg havde lavet til børnene på mit login og så fik jeg de to punkter i hovedmenuen, men indhold jeg selv afspillede på kodi endte ikke i 'fortsæt med at se', men til gengæld var der indhold jeg havde set i en browser på en anden pc på samme login.

**Comment by lars-olsen** [comment]
Er der nogle logs eller noget man kan samle op og sende til dig ?

**Comment by TermeHansen** [comment]
Det med punkterne er nok at de først dukker op næste gang du går ind i appen efter log ind. Man kan ikke rigtig ændre på menuen i det vindue der allerede er læst ind i Kodi. 

Ja , eg skal se om jeg kan finde ud af at sende data til drtv den anden vej med hvad man har afspillet, så det ved jeg godt ikke virker (endnu).
Vigtigst lige nu er at login virker og at man forbliver logget ind også over længere tid.

Imens vi tester det af vil jeg se om jeg kan reverse engineer også infomation fra Kodi tilbage til drtv om ting i min liste og fortsæt med at se...

**Comment by TermeHansen** [comment]
@lars-olsen jeg fandt lige en lille bug omkring udløbstid på tokens, så den seneste version i min branch er lidt hurtigere nu igen, da den ikke skal hente friske tokens hele tiden...

Jeg er også begyndt arbejdet med at tilføje og fjerne fra min liste, men det virker vist ikke helt i den version lige nu. Jeg roder videre med det imorgen nok.

**Comment by TermeHansen** [comment]
@lars-olsen jeg har nu tilføjelse og fjernelse fra min liste inde, og tilføjet hooks til Fortsæt med at se. Det kommer ind rigtigt nok i Kodi se der ud til, men når jeg skal starter videoen starter den stadig fra start selvom den burde starte hvor man var kommet til.

Jeg vil se om jeg kan finde ud af denne sidste del, men ellers tror jeg at jeg er tæt på at sende det til release...

**Comment by TermeHansen** [comment]
ok, jeg kan nu se at det nok kræver en del mere arbejde at få det her med resumepoint til at virke begge veje (op til drtv, og tilbage til kodi) alt efter hvor det senest er blevet afspillet. Jeg vil lade det gå til en ny update of feature setup hvor jeg skal lave en service for denne addon der hele tide overvåger om man er igang med at afspille noget.

Godt eksempel til at føle findes på https://github.com/add-ons/plugin.video.vrt.nu og PlayerInfo() klassen.

Jeg vil nu gå denne del her igennem og sende til update til alle og derefter lukke dette issue. Lad mig endelig vide hvis nogen oplever nogle issues med koden fra https://github.com/xbmc-danish-addons/plugin.video.drnu/releases/tag/v6.3.0

**Comment by lars-olsen** [comment]
@TermeHansen: vil bare sige tak for det store arbejde du laver med denne plugin. Det er virkeligt værdsat og jeg glæder mig til at tage den nye version i brug.

**Comment by TermeHansen** [comment]
Så er den sendt til officiel kodi update kanal, lad os se om den kommer igennem snart.
https://github.com/xbmc/repo-plugins/pull/4469

Jeg fik fikset så den nu også opdaterer hovedmenuen efter man har logget ind, og at der nu står ved de personlige lister hvilket navn der er logget ind for.

**Comment by TermeHansen** [comment]
@lars-olsen jeg har nu tilføjelse og fjernelse fra min liste inde, og tilføjet hooks til Fortsæt med at se. Det kommer ind rigtigt nok i Kodi se der ud til, men når jeg skal starter videoen starter den stadig fra start selvom den burde starte hvor man var kommet til.

Jeg vil se om jeg kan finde ud af denne sidste del, men ellers tror jeg at jeg er tæt på at sende det til release...

**Comment by TermeHansen** [comment]
Og nu officielt ude. Jeg lukker dette issue.

**Comment by pank** [comment]
Det ser ud til at virke fint for mig. Mange tak!

**Comment by TermeHansen** [comment]
@pank gider du hjælpe med at test det nye Gensyn område?
https://github.com/xbmc-danish-addons/plugin.video.drnu/issues/90

**Comment by pank** [comment]
Naturligvis. Jeg prøver at installere det i aften.
