### ISSUE TITLE
Fortsæt med at se (brugernavn) - crasher

### ISSUE THREAD

**Issue by steyrs** [xbmc-danish-addons/plugin.video.drnu#88]
Hej folkens.

Har lige installeret version 6.3.0 - i Kodi (på Windows)
Login til DR TV - kører fint - men når jeg trykker "Fortsæt med at se (brugernavn) - crasher addon'en med det samme.

Jeg får denne fejl i loggen (sig til, hvis der er brug for yderligere info)

[Error-dr-tv-plugin.txt](https://github.com/xbmc-danish-addons/plugin.video.drnu/files/14473437/Error-dr-tv-plugin.txt)

**Comment by TermeHansen** [comment]
Cool, thanks. I'll look into it later and get back to you.

**Comment by steyrs** [comment]
No worries TermeHansen - take your time!

And thank you for keeping this add-on alive - I find it very useful - and love being able to watch DR content from within Kodi - and not having to rely on Smart-TV apps instead!

**Comment by TermeHansen** [comment]
ok @steyrs I get why it crashes as such from the code, and have now made a fall back so it will not happen. But I would still like to understand why in your case I can't find the watched item from it's id in the list from your profile that for me at least lists the same items but also with the current time they should continue from.

I made a small branch with a bit of extra debug output for me to understand this issue better. Could you please get the zip from this branch (https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/no_resumetime_issue) or just change the files locally as here in my commit https://github.com/xbmc-danish-addons/plugin.video.drnu/commit/20dfd7546afa94539a209e40bb2f75f3d97be95e

Then please open the "Fortsæt med at se" in kodi and share the log from just this action. On my side it lloks like this:

```
2024-03-03 18:17:32.847 T:427796    info <general>: {'434309': {'position': 1103, 'firstWatchedDate': '2024-02-10T08:59:19.531Z', 'lastWatchedDate': '2024-02-23T19:53:17.317Z', 'isFullyWatched': False}, '438030': {'position': 620, 'firstWatchedDate': '2024-02-23T18:12:24.219Z', 'lastWatchedDate': '2024-02-23T20:49:45.456Z', 'isFullyWatched': False}}
2024-03-03 18:17:32.847 T:427796    info <general>: 438030

```

**Comment by steyrs** [comment]
Hello @TermeHansen 

Of course - I'm more than happy to help.
I added your modified tvapi.py to the lib folder - and gave it another shot.
And sure enough - it no longer crashes.

I have attached a new log file - containing the bits - where I open the addon and then hit "Fortsæt med at se"
Hopefully you find useful information in the log file.

Otherwise feel free to reach out - I'm more than happy to help!

[Added-code-resume-now-works.txt](https://github.com/xbmc-danish-addons/plugin.video.drnu/files/14474250/Added-code-resume-now-works.txt)

**Comment by TermeHansen** [comment]
Interesting - I can still not understand why this one item you have in continue watching is not in your rather long list of items of watching in your profile. But we are not using the resumetime feature for now, as it is not working in kodi directly for some reason. This is the feature I will start working on now.

For now I will not send this up as a new bug fix, as I expect to have the next feature ready soon. If more people have this same issue we can make a small point release.

the fix of this bug is changing this line in `ressources/lib/tvapi.py`

`            item['ResumeTime'] = float(watched[str(item['id'])]['position'])`

to
`            item['ResumeTime'] = float(watched.get(str(item['id']), {'position':0.0})['position'])`

**Comment by TermeHansen** [comment]
hmm ok, I just found a small bug that led to not seeing the two personal menu item when refreshing the tokens (after 24hour). So I will probably make a small point release, after I ave tested this branch a couple of days...

**Comment by TermeHansen** [comment]
I'll closr this issue, as 6.3.1 just has been released that fixes this issue...

**Comment by TermeHansen** [comment]
@steyrs do you mind testing

https://github.com/xbmc-danish-addons/plugin.video.drnu/issues/90

**Comment by steyrs** [comment]
@TermeHansen - been testing the pre-release version 
and haven't found any bugs so far.
I had a glitch trying "Gensyn" > "Serierne der samlede os" > "Taxa" > "Taxa. Episode 1- and skipping forward.
Playback stopped - and got stuck - ultimately ending up in Kodi freezing.

I haven't been able to reproduce the issue - so for now - I suspect a local issue on my end.
