### ISSUE TITLE
6.3.0 crashing

### ISSUE THREAD

**Issue by ABH10** [xbmc-danish-addons/plugin.video.drnu#91]
Tak for arbejdet med denne add-on.
Jeg kører Libreelec 10.0.4 med Kodi19.5 på Rpi. Har lige opdateret til 6.3.0 (fra 6.2.0) og oplever at drnu crasher i alle menupunkter, pånær Live TV.
[kodi.log](https://github.com/xbmc-danish-addons/plugin.video.drnu/files/14618515/kodi.log)

**Comment by TermeHansen** [comment]
Kodi 6.3.0 og opefter er kun lagt ud i Kodi 20 Nexus repo, så med mindre du kan give mig en god årsag havde jeg ikke tænkt mig at supporte 19 Matrix mere. Nexus har været seneste version i mere end et år, og Omega er meget snart på vej.

https://mirrors.kodi.tv/addons/matrix/plugin.video.drnu/

https://mirrors.kodi.tv/addons/nexus/plugin.video.drnu/

Mvh
Rasmus

**Comment by ABH10** [comment]
Tak for svar. Jeg må prøve Nexus.
