### ISSUE TITLE
When abroad the live channels do not work except TVA Live

### ISSUE THREAD

**Issue by krogsbell** [xbmc-danish-addons/plugin.video.drnu#93]
Logged on with userID and able to watch e.g. Barnaby, but Live channels do not work except TVA Live when in EU.

Thank you for User logon and Gensyn.

Regards
Hans

**Comment by TermeHansen** [comment]
I'll try to reproduce via vpn, elsewhere it will have to wait until ai go abroad next time...

**Comment by krogsbell** [comment]
Hej Rasmus!

Du skal bare give mig nogle adviseringer så skal jeg nok logge problemet ;-)
MVH


Hans




Den søn. 24. mar. 2024 kl. 15.42 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by TermeHansen** [comment]
ehh, kan du se det i en browser når du er logget ind?

Jeg har lige prøvet med en udenlands VPN og får:
![image](https://github.com/xbmc-danish-addons/plugin.video.drnu/assets/6922018/d0110f09-629c-43be-be82-bfeee818b3da)

**Comment by krogsbell** [comment]
Hej Rasmus!

I Kodi addon får jeg (Playback failed):

[image: image.png]

Kører jeg SmartVPN fra DK kan jeg godt se DR1 og DR2 live i Kodi.

I min browser kan jeg godt se DR1 og DR2 live

På min Chromecast med Google TV er der tit programmer som viser at de kun
må vises i DK, Grønland og Færøerne, selv om den er logget på, men den
bliver måske logget af hver gang der er en opdatering.

Jeg kører også Kodi på  min Chromecast med Google TV og benytter min
version af plugin.audio.dr.dk.netradio dagen lang

MVH

Hans




Den man. 25. mar. 2024 kl. 19.05 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by TermeHansen** [comment]
Jeg er ikke sikker på hvad du søger med dette issue. En bedre fejlmeddelelse når man forsøger at se noget man ikke kan se uden for dk?

Det lyder som om det virker (også i Kodi) med vpn slået til. Så hvad er issue helt konkret?

**Comment by pank** [comment]
Da jeg boede i udlandet tror jeg kun live tv var tilgængeligt når der var 
en særlig begivenhed, f.eks. valg. Men det var før login via mitid.

Hvis live TV virker med din dansk vpn kan du evt. slå den automatisk til 
når DR add-onet startes ved hjælp af OpenVPN forudsat at dit system kan 
installere det (e.g. LibreELEC understøtter det, Android til TV gør 
ikke).

**Comment by krogsbell** [comment]
Når man kan se DR1 og DR2 live på web, bør man samtidig kunne det i Kodi
Appen, når man er logget på i begge tilfælde.

Det er ikke meningen at man skal bruge VPN


MVH
Hans




Den man. 25. mar. 2024 kl. 19.46 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by krogsbell** [comment]
Der er desværre andre programmer, som ikke accepterer at der er VPN aktivt

MVH
 Hans




Den man. 25. mar. 2024 kl. 19.52 skrev pank ***@***.***>:

**Comment by TermeHansen** [comment]
Bare for at være helt sikker.

Du kan uden vpn aktiveret godt se live tv i din browseren?

Kodi aggerer fujdt ud som en browser (jeg har reversed engineered fra browseren), så hvis det virker i browser så bør vi også kunne få det til at virke i Kodi.

Da jeg lige brugte browser med vpn til US, fik jeg fejl, men det kan jo være en udenfor-EU ting.

**Comment by krogsbell** [comment]
Hej Rasmus!

Jeg ser DR1 og DR2 live i browser uden VPN.

Og får fejl når jeg vil se DR1 og DR2 live i Kodi uden VPN.

Er du sikker på at logon virker i tilfældet med live TV?
Er der noget logning, som jeg kan udføre?

MVH
 Hans




Den man. 25. mar. 2024 kl. 21.17 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by TermeHansen** [comment]
hvis du kan sende mig et netværks dump fra chrome browser,kan jeg se om jeg kan se om du kalder noget andet end jeg gør her fra dk.
![image](https://github.com/xbmc-danish-addons/plugin.video.drnu/assets/6922018/6da805ad-7451-4db9-89f4-86dc8fb0a34d)

i chrome åben det her "inspect" og gå til network tab.
- stop log recording (hvis den allerede kører) ved at trykke så "optageknappen" er grå længst til ventre i panelet øverst.
- vær klar ovre i browseren til at kunne klikke på en kanal
- start log recording, klik på at få vist en kanal, og tryk så på stop recording igen.
- download ("export HAR" knappen yderst til højre) og send til min mail, og så vil jeg se om jeg kan finde noget.

**Comment by krogsbell** [comment]
Hej Rasmus!

HAR fil sendt til din private mail

MVH
 Hans




Den man. 25. mar. 2024 kl. 22.55 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by krogsbell** [comment]
Hej Rasmus!

Links som f.eks. Barnaby:
https://drod20b.akamaized.net/eu/encrypted/token/02/656c4e1bc4af574840769c02/00022363080/stream_fmp4/master_manifest.m3u8?hdnea=exp=1711538242~acl=/eu/encrypted/token/02/656c4e1bc4af574840769c02/00022363080/*~hmac=5511abfe2643f41581e185a280b99cf641242e8ad78ee821685f5653c92f7d58

Kan vises i EU.

Links fra DR Live mangler alt efter ?hdnea=...

Min test giver disse links:
2024-03-26 13:42:03 addon.py: channel 'DR1' url= '
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master.m3u8'

2024-03-26 13:42:03 addon.py: channel 'DR2' url= '
https://drlive02hls.akamaized.net/hls/live/2014187/drlive02/master.m3u8'

2024-03-26 13:42:03 addon.py: channel 'TVA Live' url= '
https://drevent01hls.akamaized.net/hls/live/2014198/drevent01/master.m3u8'

2024-03-26 13:42:03 addon.py: channel 'DRTV Ekstra' url= '
https://drevent02hls.akamaized.net/hls/live/2028694/drevent02/master.m3u8?0617
'

2024-03-26 13:42:03 addon.py: channel 'DR Ramasjang' url= '
https://drlive03hls.akamaized.net/hls/live/2014190/drlive03/master.m3u8'


Så login ser ikke ud til at være aktiveret for Live kanalerne

Jeg håber at dette kan hjælpe med problemet

MVH
 Hans




Den man. 25. mar. 2024 kl. 22.55 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by TermeHansen** [comment]
@krogsbell can you please try this new test release I made:
https://github.com/xbmc-danish-addons/plugin.video.drnu/releases/tag/v6.4.1

**Comment by krogsbell** [comment]
Hej Rasmus!

Downloadede 6.4.1 zip, pakkede den ud og kopierede filerne til min Kodi
installation.

Straks var alle live kanaler aktive - mange tak

MVH
 Hans




Den ons. 27. mar. 2024 kl. 23.58 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by TermeHansen** [comment]
Den her zip, er sådan Kodi addons pakkes, så man kan bare installere med filen direkte inde fra Kodi.

Jeg laver en ny update med det her fiks en af de nærmeste dage...

**Comment by krogsbell** [comment]
Testet på Windows og Chroomecast med Kodi 20.
Den er mere stabil til at vise EU indhold end Android appen ;-)

MVH Hans
