### ISSUE TITLE
Limit on My list

### ISSUE THREAD

**Issue by olet42** [xbmc-danish-addons/plugin.video.drnu#95]
It seems like the plugin has a limit of 24 items that gets loaded, when going into it and logged into a DR account. Using version 6.4.1

**Comment by olet42** [comment]
I did a little investigation on my own and found that changing the page_size in the data variable changes the load limit up to a max of 50, so I would summazie that it requires multiple requests to DR to increase beyond that limit.

**Comment by TermeHansen** [comment]
Ahh yes, I have functions for this kind of handling, I just did not think of the case...

I'll make a branch to test and fix.

**Comment by TermeHansen** [comment]
Hi @olet42 can you please test the code in https://github.com/xbmc-danish-addons/plugin.video.drnu/pull/96

It seems to work here at least :)

**Comment by olet42** [comment]
It works here as well. Thanks for the quick fix!
