### ISSUE TITLE
Addon fails with Python 3.12 due to the use of the removed distutils package

### ISSUE THREAD

**Issue by Chroxvi** [xbmc-danish-addons/plugin.video.drnu#98]
The Python `distutils` package is used in this addon:

https://github.com/xbmc-danish-addons/plugin.video.drnu/blob/c9559eb5f5fcff131a9b9c6965e3e12800c56ab5/resources/lib/addon.py#L26

Unfortunately, the `distutils` package has been [deprecated in Python 3.10](https://docs.python.org/3.10/whatsnew/3.10.html#distutils) and [removed in Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#distutils) making this addon fail when used with Python >=3.12.

A workaround is to install `setuptools` >= 60.0.0 which includes a copy of `distutils`. However, the use of `distutils` from `setuptools` [is discouraged in favor of transitioning to more modern alternatives](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html). Specifically, for the `distutils.version`, it is recommended to transition to [`packaging.version`](https://packaging.pypa.io/en/latest/version.html).

I am not familar enough with the Kodi addon system to know if it is easy to include `packaging` as a third party dependency in the addon or if it is easier to replace the use of `distutils.version.StrictVersion` in this addon with some custom code.

**Comment by TermeHansen** [comment]
Thks @Chroxvi I'll look into a better solution for this one of the coming days...

**Comment by TermeHansen** [comment]
https://github.com/xbmc-danish-addons/plugin.video.drnu/pull/99 solves the issue, my kodi 21.1 is still on 3.11, can you confirm this solves your issue @Chroxvi ?

**Comment by Chroxvi** [comment]
Yes, I can confirm that the "remove_strictversion" branch (https://github.com/xbmc-danish-addons/plugin.video.drnu/commit/67808fc019c1f806b57ce9d881e742d0a7380d0a) works on my box with Python 3.12.4 and setuptools uninstalled.

Thanks for resolving this issue!

**Comment by TermeHansen** [comment]
thks @Chroxvi  it is being released now

https://github.com/xbmc/repo-plugins/pull/4559
